# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1197, 827)
        mainWindow.setMouseTracking(True)
        mainWindow.setStyleSheet("#mainWindow{border:none;}\n"
"QMainWindow {\n"
"    border: 1px solid #3d8ec9;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.groupBox.setStyleSheet("#groupBox {\n"
"  background-color: rgb(255, 255, 255);\n"
"  border: 0px solid #42adff;\n"
"  border-left: 0px solid rgba(29, 83, 185, 255);\n"
"  border-right: 0px solid rgba(29, 83, 185, 255);\n"
"  border-bottom: 1px solid rgba(200, 200, 200, 100);\n"
"  border-radius: 0px;\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 24px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minButton = QtWidgets.QPushButton(self.groupBox)
        self.minButton.setMinimumSize(QtCore.QSize(50, 28))
        self.minButton.setMaximumSize(QtCore.QSize(50, 28))
        self.minButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.minButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/最小化_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon)
        self.minButton.setIconSize(QtCore.QSize(20, 20))
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_5.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(self.groupBox)
        self.maxButton.setMinimumSize(QtCore.QSize(50, 28))
        self.maxButton.setMaximumSize(QtCore.QSize(50, 28))
        self.maxButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.maxButton.setLocale(QtCore.QLocale(QtCore.QLocale.Chuvash, QtCore.QLocale.Russia))
        self.maxButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/最大化_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxButton.setIcon(icon1)
        self.maxButton.setIconSize(QtCore.QSize(20, 20))
        self.maxButton.setCheckable(True)
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout_5.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.groupBox)
        self.closeButton.setMinimumSize(QtCore.QSize(50, 28))
        self.closeButton.setMaximumSize(QtCore.QSize(50, 28))
        self.closeButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/关闭_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setIconSize(QtCore.QSize(20, 20))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(10, 10, -1, 10)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_12.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(33, 245, 175, 226), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QGroupBox {\n"
"\n"
"  border: 2px solid #000000;\n"
"  padding: 20px;\n"
"  border-radius: 10px;\n"
"  font-family: \"Arial\";\n"
"  font-size: 17px;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid #333333;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d3d3d3; /* 鼠标点击时背景变成浅灰色 */\n"
"    border-color: #333333; /* 鼠标点击时边框颜色保持灰色 */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_5.setContentsMargins(-1, 0, 9, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_2.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/数据.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 2, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox.setStyleSheet("\n"
"font-size: 15px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/模型运行.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 3, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_3.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icon/文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_8.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(33, 245, 175, 226), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QGroupBox {\n"
"\n"
"  border: 2px solid #000000;\n"
"  padding: 20px;\n"
"  border-radius: 10px;\n"
"  font-family: \"Arial\";\n"
"  font-size: 17px;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 3)
        self.horizontalLayout_7.addWidget(self.widget_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.stackedWidgetPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_14 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_14.setStyleSheet("QGroupBox {\n"
"  border: 2px solid #000000;\n"
"  padding: 20px;\n"
"  border-radius: 10px;\n"
"  font-family: \"Arial\";\n"
"  font-size: 16px;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.fatigue_image_label = QtWidgets.QLabel(self.groupBox_14)
        self.fatigue_image_label.setText("")
        self.fatigue_image_label.setObjectName("fatigue_image_label")
        self.gridLayout_7.addWidget(self.fatigue_image_label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "随机结构面生成器"))
        self.label_4.setText(_translate("mainWindow", "随机结构面生成器"))
        self.groupBox_12.setTitle(_translate("mainWindow", "操作"))
        self.pushButton_2.setText(_translate("mainWindow", "选择数据"))
        self.comboBox.setItemText(0, _translate("mainWindow", "Copula"))
        self.comboBox.setItemText(1, _translate("mainWindow", "DDPM"))
        self.comboBox.setItemText(2, _translate("mainWindow", "GAN"))
        self.comboBox.setItemText(3, _translate("mainWindow", "Montecarlo"))
        self.label_2.setText(_translate("mainWindow", "选择算法"))
        self.pushButton.setText(_translate("mainWindow", "开始运行"))
        self.pushButton_3.setText(_translate("mainWindow", "工作目录"))
        self.groupBox_8.setTitle(_translate("mainWindow", "数据列表"))
        self.groupBox_14.setTitle(_translate("mainWindow", "数据可视化"))
import apprcc
